In [2]:
import datasets

dataset=datasets.load_dataset("paws", "labeled_final")

X_train1 = [x['sentence1'] for x in dataset['train']]
X_train2 = [x['sentence2'] for x in dataset['train']]
y_train = [x['label'] for x in dataset['train']]

X_test1 = [x['sentence1'] for x in dataset['test']]
X_test2 = [x['sentence2'] for x in dataset['test']]
y_test = [x['label'] for x in dataset['test']]


/home/ansh/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
from sentence_transformers import SentenceTransformer

# model_id = "bert-base-nli-mean-tokens"
model_id="all-mpnet-base-v2"
model = SentenceTransformer(model_id)

In [4]:
from sentence_transformers import InputExample

numData = len(X_train1)
train_examples = [InputExample(texts=[X_train1[i], X_train2[i]], label=y_train[i]) for i in range(int(numData))]

from torch.utils.data import DataLoader

train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=3)


In [5]:
from sentence_transformers import losses

loss = losses.ContrastiveLoss(model=model)

In [6]:
# model.to("cuda")
# model.fit(train_objectives=[(train_dataloader, loss)], epochs=10)
# model.save("paws-contrastive-v2-"+model_id)

In [7]:
from sentence_transformers import util

count=0
threshhold=0.9
for i in range(len(X_test1)):
    emb1 = model.encode(X_test1[i])
    emb2 = model.encode(X_test2[i])
    sim = util.dot_score(emb1, emb2)
    print(sim,"Label:",y_test[i])
    if sim > threshhold:
        if y_test[i]==1:
            count+=1
    else:
        if y_test[i]==0:
            count+=1
    print("Accuracy:",count/(i+1))
    print(i,'/',len(X_test1))
    print()


tensor([[0.8654]]) Label: 0
Accuracy: 1.0
0 / 8000

tensor([[0.9930]]) Label: 0
Accuracy: 0.5
1 / 8000

tensor([[0.9866]]) Label: 1
Accuracy: 0.6666666666666666
2 / 8000

tensor([[0.9517]]) Label: 0
Accuracy: 0.5
3 / 8000

tensor([[0.9971]]) Label: 0
Accuracy: 0.4
4 / 8000

tensor([[0.9869]]) Label: 1
Accuracy: 0.5
5 / 8000

tensor([[0.9059]]) Label: 0
Accuracy: 0.42857142857142855
6 / 8000

tensor([[0.9963]]) Label: 1
Accuracy: 0.5
7 / 8000

tensor([[0.9818]]) Label: 0
Accuracy: 0.4444444444444444
8 / 8000

tensor([[0.9869]]) Label: 1
Accuracy: 0.5
9 / 8000

tensor([[0.9748]]) Label: 1
Accuracy: 0.5454545454545454
10 / 8000

tensor([[0.9866]]) Label: 0
Accuracy: 0.5
11 / 8000

tensor([[0.9868]]) Label: 1
Accuracy: 0.5384615384615384
12 / 8000

tensor([[0.9590]]) Label: 1
Accuracy: 0.5714285714285714
13 / 8000

tensor([[0.9675]]) Label: 0
Accuracy: 0.5333333333333333
14 / 8000

tensor([[0.9865]]) Label: 0
Accuracy: 0.5
15 / 8000

tensor([[0.9863]]) Label: 1
Accuracy: 0.5294117647058824

In [8]:
model= SentenceTransformer("Tuned")
emb1 = model.encode(X_test1)
print("emb1 done")
emb2 = model.encode(X_test2)


emb1 done


In [9]:
count=0
threshhold=0.9

for i in range(len(X_test1)):
    sim = util.dot_score(emb1[i], emb2[i])
    print(sim,"Label:",y_test[i])
    if sim > threshhold:
        if y_test[i]==1:
            count+=1
    else:
        if y_test[i]==0:
            count+=1
    print("Accuracy:",count/(i+1))
    print(i,'/',len(X_test1))
    print()

tensor([[0.8106]]) Label: 0
Accuracy: 1.0
0 / 8000

tensor([[0.7528]]) Label: 0
Accuracy: 1.0
1 / 8000

tensor([[0.9518]]) Label: 1
Accuracy: 1.0
2 / 8000

tensor([[0.8437]]) Label: 0
Accuracy: 1.0
3 / 8000

tensor([[0.9730]]) Label: 0
Accuracy: 0.8
4 / 8000

tensor([[0.9892]]) Label: 1
Accuracy: 0.8333333333333334
5 / 8000

tensor([[0.8816]]) Label: 0
Accuracy: 0.8571428571428571
6 / 8000

tensor([[0.9954]]) Label: 1
Accuracy: 0.875
7 / 8000

tensor([[0.6662]]) Label: 0
Accuracy: 0.8888888888888888
8 / 8000

tensor([[0.9893]]) Label: 1
Accuracy: 0.9
9 / 8000

tensor([[0.9038]]) Label: 1
Accuracy: 0.9090909090909091
10 / 8000

tensor([[0.6797]]) Label: 0
Accuracy: 0.9166666666666666
11 / 8000

tensor([[0.9671]]) Label: 1
Accuracy: 0.9230769230769231
12 / 8000

tensor([[0.7690]]) Label: 1
Accuracy: 0.8571428571428571
13 / 8000

tensor([[0.9501]]) Label: 0
Accuracy: 0.8
14 / 8000

tensor([[0.9591]]) Label: 0
Accuracy: 0.75
15 / 8000

tensor([[0.9879]]) Label: 1
Accuracy: 0.76470588235294

In [10]:
model= SentenceTransformer("Tuned-v2")
count=0
threshhold=0.9
outputs=[]
emb1 = model.encode(X_test1)
print("emb1 done")
emb2 = model.encode(X_test2)

emb1 done


In [12]:
threshhold=0.8962228298187255
count=0

for i in range(len(X_test1)):
    sim = util.dot_score(emb1[i], emb2[i])
    print(sim,"Label:",y_test[i])
    if sim > threshhold:
        if y_test[i]==1:
            count+=1
    else:
        if y_test[i]==0:
            count+=1
    print("Accuracy:",count/(i+1))
    print(i,'/',len(X_test1))
    print()
    outputs.append([sim.item(),y_test[i]])

# with open("threshholdFinder.txt","w") as f:
#     for i in range(len(outputs)):
#         f.write(str(outputs[i]))
#         f.write("\n")

tensor([[0.4547]]) Label: 0
Accuracy: 1.0
0 / 8000

tensor([[0.2567]]) Label: 0
Accuracy: 1.0
1 / 8000

tensor([[0.9844]]) Label: 1
Accuracy: 1.0
2 / 8000

tensor([[0.5617]]) Label: 0
Accuracy: 1.0
3 / 8000

tensor([[0.2595]]) Label: 0
Accuracy: 1.0
4 / 8000

tensor([[0.9982]]) Label: 1
Accuracy: 1.0
5 / 8000

tensor([[0.7092]]) Label: 0
Accuracy: 1.0
6 / 8000

tensor([[0.9981]]) Label: 1
Accuracy: 1.0
7 / 8000

tensor([[0.2255]]) Label: 0
Accuracy: 1.0
8 / 8000

tensor([[0.9994]]) Label: 1
Accuracy: 1.0
9 / 8000

tensor([[0.9954]]) Label: 1
Accuracy: 1.0
10 / 8000

tensor([[0.8552]]) Label: 0
Accuracy: 1.0
11 / 8000

tensor([[0.9818]]) Label: 1
Accuracy: 1.0
12 / 8000

tensor([[0.8128]]) Label: 1
Accuracy: 0.9285714285714286
13 / 8000

tensor([[0.8645]]) Label: 0
Accuracy: 0.9333333333333333
14 / 8000

tensor([[0.3635]]) Label: 0
Accuracy: 0.9375
15 / 8000

tensor([[0.9928]]) Label: 1
Accuracy: 0.9411764705882353
16 / 8000

tensor([[0.9251]]) Label: 0
Accuracy: 0.8888888888888888
17 /